export type Question = {
  id: string;
  question: string;
  options: { A: string; B: string; C: string; D: string };
  correct: "A" | "B" | "C" | "D";
};

export type CategoryQuestions = {
  questions: Question[];
  config: { count: number; passPercent: number; timeLimitMin: number };
};

const q = (
  id: string,
  question: string,
  A: string,
  B: string,
  C: string,
  D: string,
  correct: "A" | "B" | "C" | "D"
): Question => ({ id, question, options: { A, B, C, D }, correct });

const BANK: Record<string, CategoryQuestions> = {
  "ai-content": {
    config: { count: 10, passPercent: 70, timeLimitMin: 20 },
    questions: [
      q("ac1", "What is the primary purpose of prompt engineering?",
        "Designing graphics for AI tools",
        "Crafting precise instructions to guide AI output",
        "Writing code to train new language models",
        "Building content management systems",
        "B"),
      q("ac2", "Which metric matters most for AI blog post SEO performance?",
        "Total word count per article",
        "Number of images per post",
        "Organic search ranking and click-through rate",
        "Daily publishing frequency",
        "C"),
      q("ac3", "In AI, 'hallucination' refers to:",
        "Generating creative fictional stories",
        "Producing confident but factually incorrect information",
        "Unusually fast text generation",
        "Repeating the same sentence multiple times",
        "B"),
      q("ac4", "A 'few-shot prompt' is best described as:",
        "A single-word minimal prompt",
        "A prompt containing multiple examples to guide the AI",
        "A technique to cut API costs",
        "A prompt sent in bulk batches",
        "B"),
      q("ac5", "Content repurposing primarily involves:",
        "Translating content to another language",
        "Copying competitor articles with minor edits",
        "Adapting one piece of content into multiple formats",
        "Deleting old low-traffic content",
        "C"),
      q("ac6", "Which practice violates Google's content quality policies?",
        "Using AI to brainstorm topic ideas",
        "AI drafts that human editors then refine",
        "Publishing bulk AI content solely for ranking manipulation",
        "Grammar correction using AI tools",
        "C"),
      q("ac7", "When selecting a content niche, the FIRST step should be:",
        "Choosing the most profitable keyword cluster",
        "Building a social media following first",
        "Identifying a target audience and their specific pain points",
        "Selecting the cheapest AI writing tool",
        "C"),
      q("ac8", "Which income stream typically yields the highest revenue for content creators?",
        "Selling ad space directly on a blog",
        "Affiliate marketing on high-ticket products",
        "Generic social media posts",
        "Automated bulk email newsletters",
        "B"),
      q("ac9", "An effective content calendar primarily helps creators:",
        "Replace the need for original ideas entirely",
        "Automate publishing across all platforms",
        "Maintain consistent topics and publishing schedule",
        "Maximise word count per article",
        "C"),
      q("ac10", "The BEST way to build authority as an AI content creator is:",
        "Publishing daily regardless of quality",
        "Using as many AI tools simultaneously as possible",
        "Focusing on a specific niche and demonstrating deep expertise",
        "Maximising the number of prompts used",
        "C"),
    ],
  },

  "data-analyst": {
    config: { count: 10, passPercent: 70, timeLimitMin: 20 },
    questions: [
      q("da1", "What is the key difference between correlation and causation?",
        "Correlation is always stronger than causation",
        "Correlation shows relationship; causation proves one variable causes the other",
        "They mean the same thing statistically",
        "Causation is measured with Pearson's r",
        "B"),
      q("da2", "For visualising a continuous trend over time, the MOST appropriate chart is:",
        "Line chart",
        "Pie chart",
        "Stacked bar chart",
        "Bubble chart",
        "A"),
      q("da3", "Overfitting in a machine learning model means:",
        "The model trains too slowly",
        "The model uses too much GPU memory",
        "The model memorises training data and generalises poorly",
        "The model has too many input features",
        "C"),
      q("da4", "A p-value below 0.05 typically indicates:",
        "The effect is practically meaningful",
        "The result is statistically significant at the 5% level",
        "The null hypothesis is definitely true",
        "The sample size is insufficient",
        "B"),
      q("da5", "Feature engineering in ML primarily involves:",
        "Creating informative input variables to improve model performance",
        "Designing neural network layer architectures",
        "Selecting the optimal model algorithm",
        "Cleaning missing values only",
        "A"),
      q("da6", "In a confusion matrix, 'precision' measures:",
        "All correctly classified instances divided by total",
        "True positives divided by all actual positives (recall)",
        "True positives divided by all predicted positives",
        "Overall model accuracy across all classes",
        "C"),
      q("da7", "Principal Component Analysis (PCA) is used to:",
        "Detect outliers and anomalies in datasets",
        "Reduce the number of features while retaining most variance",
        "Fill in missing values across columns",
        "Increase the accuracy of regression models",
        "B"),
      q("da8", "Data normalisation is primarily used to:",
        "Scale features to a comparable numerical range",
        "Remove duplicate records from a dataset",
        "Encode categorical variables as integers",
        "Split data into training and test sets",
        "A"),
      q("da9", "Cross-validation in machine learning is used to:",
        "Speed up model training on large datasets",
        "Assess model performance and reduce overfitting risk",
        "Generate synthetic training data",
        "Select the optimal loss function",
        "B"),
      q("da10", "Which analysis identifies which variables MOST influence a target outcome?",
        "Cluster analysis",
        "Time series decomposition",
        "Feature importance / permutation analysis",
        "Market basket analysis",
        "C"),
    ],
  },

  "developer": {
    config: { count: 10, passPercent: 70, timeLimitMin: 20 },
    questions: [
      q("dev1", "Fine-tuning a language model involves:",
        "Adjusting API rate limits for production",
        "Further training on domain-specific data to specialise behaviour",
        "Choosing the right model size for your use case",
        "Optimising prompt response latency",
        "B"),
      q("dev2", "Retrieval Augmented Generation (RAG) primarily solves:",
        "Training models on larger datasets faster",
        "Reducing hallucinations by grounding responses in retrieved documents",
        "Speeding up inference API response times",
        "Reducing model parameter count",
        "B"),
      q("dev3", "What is 'prompt injection' in AI security?",
        "Injecting prompts via HTTP POST body",
        "Malicious input designed to override system instructions",
        "Injecting code into model weights directly",
        "Caching common prompt responses",
        "B"),
      q("dev4", "Which architecture underpins most modern large language models?",
        "Convolutional Neural Network (CNN)",
        "Recurrent Neural Network (RNN)",
        "Transformer",
        "Generative Adversarial Network (GAN)",
        "C"),
      q("dev5", "A 'system prompt' in LLM APIs is used to:",
        "Set the user question text",
        "Define the model's behaviour and persona for the session",
        "Specify the API endpoint URL",
        "Set per-request rate limits",
        "B"),
      q("dev6", "Serverless AI deployments are BEST suited for:",
        "High-throughput GPU video rendering",
        "Continuous model training jobs",
        "Event-driven APIs with variable and unpredictable load",
        "Real-time 4K video processing pipelines",
        "C"),
      q("dev7", "Token limits in LLM APIs refer to:",
        "API authentication token expiry times",
        "The maximum combined length of input + output text",
        "The number of API requests per minute",
        "Server-side memory allocation",
        "B"),
      q("dev8", "Which technique MOST effectively reduces AI hallucinations in production?",
        "Increasing the temperature parameter",
        "Using RAG to ground responses in verified source documents",
        "Reducing the context window size",
        "Disabling the system prompt entirely",
        "B"),
      q("dev9", "Embeddings in AI development represent:",
        "Database indexes for fast record lookup",
        "Compressed images used in model training",
        "Dense numerical vector representations of text or data",
        "API keys encoded in base64 format",
        "C"),
      q("dev10", "The principle of AI transparency requires:",
        "Open-sourcing all model weights publicly",
        "Making AI decision-making processes understandable to affected users",
        "Sharing all training data under open licences",
        "Restricting AI to pre-approved use cases only",
        "B"),
    ],
  },

  "marketer": {
    config: { count: 10, passPercent: 70, timeLimitMin: 20 },
    questions: [
      q("mk1", "In digital marketing, a 'conversion' most commonly refers to:",
        "Changing a website's visual design",
        "A visitor completing a desired action (purchase, sign-up)",
        "Converting ad spend to a different currency",
        "Migrating from one ad platform to another",
        "B"),
      q("mk2", "Which metric measures the cost to acquire one paying customer?",
        "CPM (Cost Per Mille)",
        "CTR (Click-Through Rate)",
        "CAC (Customer Acquisition Cost)",
        "ROAS (Return on Ad Spend)",
        "C"),
      q("mk3", "A/B testing in digital marketing involves:",
        "Testing two completely different audience segments",
        "Running two variants of an element to determine the better performer",
        "Comparing two competitor campaign strategies",
        "Testing layouts on both mobile and desktop simultaneously",
        "B"),
      q("mk4", "ROAS (Return on Ad Spend) is calculated as:",
        "Revenue divided by ad spend",
        "Clicks divided by impressions",
        "Conversions divided by total ad spend",
        "Revenue minus cost of goods sold",
        "A"),
      q("mk5", "Which platform has the highest average B2B engagement rate?",
        "TikTok",
        "Instagram",
        "LinkedIn",
        "Pinterest",
        "C"),
      q("mk6", "In email marketing, the MOST important indicators of list health are:",
        "Total subscriber count and list growth rate",
        "Open rate trends and unsubscribe rate",
        "Email send frequency and template design",
        "Subject line character count",
        "B"),
      q("mk7", "The awareness stage of a marketing funnel is BEST served by:",
        "Retargeting existing customers with loyalty offers",
        "Upselling premium features to active users",
        "Broad reach content and wide-audience paid impressions",
        "Referral and loyalty programmes",
        "C"),
      q("mk8", "The PRIMARY benefit of marketing automation is:",
        "Replacing the entire marketing team with software",
        "Delivering personalised messages at scale with minimal manual effort",
        "Automatically generating creative assets",
        "Eliminating paid advertising costs",
        "B"),
      q("mk9", "'Lookalike audiences' in paid advertising are used to:",
        "Clone existing successful ad creatives",
        "Target users who resemble your best existing customers",
        "Retarget users who visited your website",
        "Research and target competitors' audiences",
        "B"),
      q("mk10", "Conversion Rate Optimisation (CRO) primarily focuses on:",
        "Increasing overall website traffic volume",
        "Improving the percentage of visitors who complete a desired action",
        "Reducing total advertising budget spend",
        "Improving page load speeds and Core Web Vitals",
        "B"),
    ],
  },

  "tutor": {
    config: { count: 10, passPercent: 70, timeLimitMin: 20 },
    questions: [
      q("tu1", "Which learning theory emphasises learning through active experience and doing?",
        "Behaviourism",
        "Cognitivism",
        "Constructivism",
        "Connectivism",
        "C"),
      q("tu2", "Spaced repetition in learning is MOST effective for:",
        "Solving novel creative problems",
        "Long-term retention of factual information",
        "Speed reading comprehension",
        "Collaborative group projects",
        "B"),
      q("tu3", "When designing an online course, the FIRST step should be:",
        "Recording all video lectures",
        "Setting the course price and payment model",
        "Defining clear, measurable learning outcomes",
        "Choosing a hosting platform",
        "C"),
      q("tu4", "'Formative assessment' differs from 'summative assessment' in that it:",
        "Occurs only at the end of a course",
        "Results in a final grade or certification",
        "Provides ongoing feedback during the learning process",
        "Tests only theoretical knowledge without application",
        "C"),
      q("tu5", "AI-powered adaptive learning platforms primarily:",
        "Replace human tutors entirely",
        "Personalise content difficulty based on individual learner performance",
        "Automatically issue course certificates",
        "Schedule and run live tutoring sessions",
        "B"),
      q("tu6", "'Gamification' in education is best described as:",
        "Teaching students exclusively through video games",
        "Adding game elements like points and badges to increase engagement",
        "Making courses free-to-play with optional paid upgrades",
        "Using game design software to build presentations",
        "B"),
      q("tu7", "Which approach BEST addresses diverse learning styles in a course?",
        "Using only text-based reading materials",
        "Providing multiple content formats: video, text, audio, interactive",
        "Requiring students to take handwritten notes",
        "Progressively increasing difficulty without variety",
        "B"),
      q("tu8", "A Learning Management System (LMS) is primarily used to:",
        "Manage tutor payroll and invoicing",
        "Deliver, track, and manage educational content and learner progress",
        "Create AI-generated lesson plans",
        "Book and schedule physical classroom sessions",
        "B"),
      q("tu9", "The MOST effective strategy for increasing course completion rates is:",
        "Shortening courses regardless of content depth",
        "Adding more quizzes and tests",
        "Building community and providing accountability checkpoints",
        "Offering unconditional refunds",
        "C"),
      q("tu10", "'Value-based pricing' for tutoring services means:",
        "Charging the lowest price available in the market",
        "Pricing based on your hourly time cost",
        "Setting prices according to the outcomes and transformation you deliver",
        "Matching competitor prices exactly",
        "C"),
    ],
  },

  "video-editor": {
    config: { count: 10, passPercent: 70, timeLimitMin: 20 },
    questions: [
      q("ve1", "Colour grading in video production involves:",
        "Rating videos by production quality",
        "Adjusting colour tones and mood to achieve a desired aesthetic look",
        "Converting video files between different formats",
        "Adding colour-coded chapter annotations",
        "B"),
      q("ve2", "Which video format offers the BEST quality-to-file-size ratio for web delivery?",
        "AVI",
        "MOV (ProRes)",
        "H.264/MP4",
        "RAW",
        "C"),
      q("ve3", "'B-roll' footage in video editing refers to:",
        "The main interview or talking-head shots",
        "Low-quality backup footage for safety",
        "Supplementary footage that illustrates or supports the main narrative",
        "Behind-the-scenes raw unedited footage",
        "C"),
      q("ve4", "A LUT (Look-Up Table) in video editing is used for:",
        "Organising project file and folder structures",
        "Applying pre-set colour transformations in one step",
        "Converting audio tracks to different formats",
        "Creating automated subtitle templates",
        "B"),
      q("ve5", "The frame rate BEST suited for a cinematic film look is:",
        "60fps",
        "120fps",
        "24fps",
        "30fps",
        "C"),
      q("ve6", "AI auto-captioning tools primarily use which underlying technology?",
        "Computer vision object detection",
        "Automatic Speech Recognition (ASR)",
        "Natural language text generation",
        "Image segmentation algorithms",
        "B"),
      q("ve7", "For YouTube Partner Program monetisation, the watch time requirement is:",
        "500 public watch hours in the past 12 months",
        "4,000 public watch hours in the past 12 months",
        "1,000 watch hours within 6 months",
        "10,000 total lifetime watch hours",
        "B"),
      q("ve8", "A 'J-cut' in video editing means:",
        "A jump cut that removes frames abruptly",
        "A colour correction technique for skin tones",
        "The audio from the next scene begins before its video appears",
        "A motion graphics transition effect",
        "C"),
      q("ve9", "Which aspect ratio is standard for YouTube and most social video content?",
        "4:3",
        "21:9",
        "16:9",
        "1:1",
        "C"),
      q("ve10", "Text-to-video AI tools are used to:",
        "Generate voiceovers from written scripts",
        "Generate visual video content from text descriptions",
        "Create subtitles from video audio automatically",
        "Generate video thumbnails from title text",
        "B"),
    ],
  },

  "crypto": {
    config: { count: 10, passPercent: 70, timeLimitMin: 20 },
    questions: [
      q("cr1", "A blockchain's 'consensus mechanism' is responsible for:",
        "Encrypting user wallet private keys",
        "Agreeing on the valid ledger state without central authority",
        "Setting exchange rates for cryptocurrencies",
        "Managing user identity verification",
        "B"),
      q("cr2", "DeFi stands for:",
        "Digital Finance",
        "Decentralised Finance",
        "Distributed Funding Interface",
        "Direct Fund Investment",
        "B"),
      q("cr3", "An Automated Market Maker (AMM) works by:",
        "Matching buyers and sellers using order books",
        "Automatically rebalancing investor portfolios",
        "Using liquidity pools and formulas to price assets",
        "Automating trades based on technical chart patterns",
        "C"),
      q("cr4", "'Impermanent loss' in DeFi liquidity provision occurs when:",
        "A smart contract vulnerability is exploited",
        "The price ratio of pooled assets changes from your deposit time",
        "Gas fees on transactions exceed earned trading fees",
        "Staking reward distribution is delayed",
        "B"),
      q("cr5", "'Gas' in Ethereum refers to:",
        "The electrical energy consumed during mining",
        "The transaction fee paid to validators for processing",
        "A measure of current network congestion level",
        "The speed at which transactions are confirmed",
        "B"),
      q("cr6", "A hardware wallet provides security by:",
        "Storing crypto balances on a regulated exchange",
        "Generating a new public key for every transaction",
        "Keeping private keys offline in a physical device",
        "Requiring multi-signature approvals for all transactions",
        "C"),
      q("cr7", "The Sharpe Ratio in portfolio analysis measures:",
        "Total absolute portfolio returns",
        "Risk-adjusted return per unit of volatility",
        "Maximum portfolio drawdown from peak",
        "Correlation between individual asset prices",
        "B"),
      q("cr8", "Dollar-Cost Averaging (DCA) in crypto investing means:",
        "Converting crypto profits to USD on a schedule",
        "Investing a fixed amount at regular intervals regardless of price",
        "Averaging down your cost basis after a losing trade",
        "Splitting investments across multiple exchanges",
        "B"),
      q("cr9", "A smart contract is BEST defined as:",
        "A legally binding digital contract stored in the cloud",
        "An AI-powered algorithmic trading bot",
        "Self-executing code on a blockchain that runs when conditions are met",
        "A multi-signature approval agreement between parties",
        "C"),
      q("cr10", "Portfolio rebalancing in crypto means:",
        "Withdrawing a portion of profits on a schedule",
        "Restoring asset allocations back to target percentages",
        "Diversifying into newly launched blockchain networks",
        "Converting all volatile assets to stablecoins",
        "B"),
    ],
  },
};

export function getCategoryQuestions(categoryId: string): CategoryQuestions | null {
  return BANK[categoryId] ?? null;
}
