[phases.setup]
nixPkgs = ["nodejs_20", "python3"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run server:build",
  "npx prisma generate"
]

[start]
cmd = "npx prisma migrate deploy && npm run server:start"
