-- CreateEnum
CREATE TYPE "UserRank" AS ENUM ('MEMBER', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'DIAMOND', 'BILLIONAIRE', 'BILLIONAIRE_ELITE');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "rank" "UserRank" NOT NULL DEFAULT 'MEMBER';
